# Generated by Django 3.1.1 on 2020-09-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_review_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
