# Generated by Django 3.1.1 on 2020-09-18 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_scores', to='games.game')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_scores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=100)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='games.game')),
            ],
        ),
        migrations.CreateModel(
            name='GameScoreParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('gamescore_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_score_parameters', to='games.gamescore')),
                ('parameter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_score_parameters', to='games.parameter')),
            ],
        ),
    ]
