# Generated by Django 3.1.1 on 2020-09-18 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_gamescore_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamescoreparameters',
            options={'verbose_name_plural': 'Game score parameters'},
        ),
    ]
