# Generated by Django 3.1.1 on 2020-09-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20200918_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(default='foo', unique=True),
            preserve_default=False,
        ),
    ]
