# Generated by Django 3.1.1 on 2020-09-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20200920_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='slug',
            field=models.SlugField(default='foo', editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameter',
            name='values',
            field=models.JSONField(default='foo'),
            preserve_default=False,
        ),
    ]
