# Generated by Django 3.1.1 on 2020-09-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20200921_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='default_value',
            field=models.CharField(default='foo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameter',
            name='input_type',
            field=models.CharField(choices=[('select', 'select'), ('number', 'number')], default='foo', max_length=50),
            preserve_default=False,
        ),
    ]
