# Generated by Django 3.1.1 on 2020-09-23 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20200921_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='input_type',
        ),
    ]
