# Generated by Django 3.1.1 on 2020-09-24 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_auto_20200924_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameter',
            old_name='parameter_values',
            new_name='values',
        ),
    ]
