# Generated by Django 3.1.1 on 2020-09-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_auto_20200924_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametervalue',
            name='key',
        ),
        migrations.AlterField(
            model_name='parametervalue',
            name='value',
            field=models.CharField(help_text='Value should be uppercase word.', max_length=50),
        ),
    ]
