# Generated by Django 3.1.1 on 2020-09-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_auto_20200924_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescore',
            name='parameter_values',
            field=models.ManyToManyField(related_name='game_scores', to='games.ParameterValue'),
        ),
        migrations.DeleteModel(
            name='GameScoreParameters',
        ),
    ]
