# Generated by Django 3.1.1 on 2020-09-25 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_auto_20200924_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='values',
        ),
        migrations.AddField(
            model_name='parametervalue',
            name='parameter',
            field=models.ForeignKey(
                default=3, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='games.parameter'),
            preserve_default=False,
        ),
    ]
