# Generated by Django 3.1.1 on 2020-09-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_auto_20200928_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametervalue',
            options={'ordering': ['parameter', 'ordering_name']},
        ),
        migrations.AddField(
            model_name='parametervalue',
            name='ordering_name',
            field=models.CharField(default='foo', max_length=50),
            preserve_default=False,
        ),
    ]
