# Generated by Django 3.1.1 on 2020-09-29 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_auto_20200928_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametervalue',
            options={'ordering': ['parameter', 'value']},
        ),
    ]
