# Generated by Django 3.1.1 on 2020-09-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0019_auto_20200929_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametervalue',
            name='ordering_name',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='parametervalue',
            name='slug',
            field=models.SlugField(default='foo', editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parametervalue',
            name='value',
            field=models.CharField(help_text='Value should be uppercase word. Numbers must be less than 10 digits             without chars to order properly.', max_length=50),
        ),
    ]
