# Generated by Django 3.1.1 on 2020-09-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0020_auto_20200929_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
