# Generated by Django 3.1.1 on 2020-10-01 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0021_auto_20200929_1028'),
        ('games', '0021_game_description'),
    ]

    operations = [
    ]
